#!/usr/bin/env bash
set -euo pipefail

# Qwen3.5-9B A9 certificate-grounded process supervision.
# Keep the verifier/reward contract identical to the 4B launcher while using
# conservative 8-GPU settings for the larger actor.

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(cd "$HERE/../../.." && pwd)"

export HOTPOTQA_REWARD_ARM=A9_CERT_MIX
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}"
export HOTPOTQA_NUM_GPUS="${HOTPOTQA_NUM_GPUS:-8}"
export HOTPOTQA_MODEL_PATH="${HOTPOTQA_MODEL_PATH:-$WORKSPACE_DIR/models/Qwen3.5-9B}"
export AGENT_R1_MODEL_SCALE="${AGENT_R1_MODEL_SCALE:-9b}"
export AGENT_R1_LORA_RANK="${AGENT_R1_LORA_RANK:-64}"
export HOTPOTQA_A9_EM_WARMUP_STEPS="${HOTPOTQA_A9_EM_WARMUP_STEPS:-50}"
export HOTPOTQA_A9_FORMAT_GATE=1
export HOTPOTQA_A9_FORMAT_PENALTY=0
export HOTPOTQA_VLLM_ENABLE_SLEEP_MODE=false
export HOTPOTQA_VLLM_FREE_CACHE_ENGINE=false
export HOTPOTQA_SKIP_PREFLIGHT="${HOTPOTQA_SKIP_PREFLIGHT:-0}"

# 9B memory window: batch of 8, 4 rollouts per prompt, smaller validation batches,
# bounded vLLM concurrency, and actor/optimizer offload.
export HOTPOTQA_RUN_MODE="${HOTPOTQA_RUN_MODE:-main}"
export HOTPOTQA_TRAIN_BATCH_SIZE="${HOTPOTQA_TRAIN_BATCH_SIZE:-8}"
export HOTPOTQA_ROLLOUT_N="${HOTPOTQA_ROLLOUT_N:-4}"
export HOTPOTQA_GRPO_MICRO_BATCH_SIZE="${HOTPOTQA_GRPO_MICRO_BATCH_SIZE:-1}"
export HOTPOTQA_VAL_BATCH_SIZE="${HOTPOTQA_VAL_BATCH_SIZE:-4}"
export HOTPOTQA_VLLM_GPU_MEMORY_UTILIZATION="${HOTPOTQA_VLLM_GPU_MEMORY_UTILIZATION:-0.25}"
export HOTPOTQA_VLLM_MAX_MODEL_LEN="${HOTPOTQA_VLLM_MAX_MODEL_LEN:-12288}"
export HOTPOTQA_VLLM_MAX_NUM_BATCHED_TOKENS="${HOTPOTQA_VLLM_MAX_NUM_BATCHED_TOKENS:-12288}"
export HOTPOTQA_VLLM_MAX_NUM_SEQS="${HOTPOTQA_VLLM_MAX_NUM_SEQS:-32}"
export HOTPOTQA_ACTOR_USE_DYNAMIC_BSZ="${HOTPOTQA_ACTOR_USE_DYNAMIC_BSZ:-true}"
export HOTPOTQA_ACTOR_MAX_TOKEN_LEN_PER_GPU="${HOTPOTQA_ACTOR_MAX_TOKEN_LEN_PER_GPU:-8192}"
export HOTPOTQA_ACTOR_PARAM_OFFLOAD="${HOTPOTQA_ACTOR_PARAM_OFFLOAD:-true}"
export HOTPOTQA_ACTOR_OPTIMIZER_OFFLOAD="${HOTPOTQA_ACTOR_OPTIMIZER_OFFLOAD:-true}"
export HOTPOTQA_SAVE_FREQ="${HOTPOTQA_SAVE_FREQ:-50}"
export HOTPOTQA_MAX_ACTOR_CKPT_TO_KEEP="${HOTPOTQA_MAX_ACTOR_CKPT_TO_KEEP:-2}"

export RUN_ID="${RUN_ID:-qwen35-9b_a9_certmix_uniform_main10k_n4_8gpu_$(date +%Y%m%d-%H%M%S)}"

exec bash "$HERE/run_rlvr.sh" "$@"
