#!/usr/bin/env bash
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$HERE/../.." && pwd)"
WORKSPACE_DIR="$(cd "$PROJECT_DIR/.." && pwd)"

export HOTPOTQA_LR_EVAL_MODE=calibration
export HOTPOTQA_LR_REASON_STEP_FORMAT="${HOTPOTQA_LR_REASON_STEP_FORMAT:-dsl}"
export HOTPOTQA_MODEL_PATH="${HOTPOTQA_MODEL_PATH:-$WORKSPACE_DIR/models/Qwen3.5-4B}"
export HOTPOTQA_TRAIN_PATH="${HOTPOTQA_TRAIN_PATH:-$PROJECT_DIR/data/corpus/hotpotqa/train.parquet}"
export HOTPOTQA_VAL_PATH="$HOTPOTQA_TRAIN_PATH"
export HOTPOTQA_VAL_MAX_SAMPLES=64
export HOTPOTQA_VAL_N=8
export HOTPOTQA_VAL_DO_SAMPLE=true
export HOTPOTQA_VAL_TEMPERATURE=1.0
export HOTPOTQA_VAL_TOP_P=1
export HOTPOTQA_VAL_TOP_K=-1
export HOTPOTQA_CALIBRATION_SEED="${HOTPOTQA_CALIBRATION_SEED:-42}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-1,3,4,5,6,7}"
export HOTPOTQA_NUM_GPUS=6
export HOTPOTQA_AGENT_WORKERS=6
export HOTPOTQA_TRAIN_BATCH_SIZE=12
export HOTPOTQA_VLLM_GPU_MEMORY_UTILIZATION=0.25
export HOTPOTQA_VLLM_MAX_MODEL_LEN=8192
export HOTPOTQA_VLLM_MAX_NUM_BATCHED_TOKENS=8192
export HOTPOTQA_VLLM_MAX_NUM_SEQS=20
export RAY_TMPDIR="${RAY_TMPDIR:-/dev/shm/a8c-${UID}-$$}"
export RUN_ID="${RUN_ID:-qwen35-4b_a8v2_${HOTPOTQA_LR_REASON_STEP_FORMAT}_calibration64_n8_6gpu_vllm025_mlen8192_mseq20_autokv_$(date +%Y%m%d-%H%M%S)}"
export VALIDATION_DATA_DIR="${VALIDATION_DATA_DIR:-$WORKSPACE_DIR/logs/$RUN_ID}"

exec bash "$HERE/run_validation.sh"
