#!/usr/bin/env bash
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$HERE/../.." && pwd)"
WORKSPACE_DIR="$(cd "$PROJECT_DIR/.." && pwd)"

export HOTPOTQA_REWARD_ARM=A8_LR30_CS
export HOTPOTQA_LR_REASON_STEP_FORMAT=claim_source
export HOTPOTQA_LR_EM_WARMUP_STEPS="${HOTPOTQA_LR_EM_WARMUP_STEPS:-100}"
export HOTPOTQA_RUN_MODE=main
export HOTPOTQA_MODEL_PATH="${HOTPOTQA_MODEL_PATH:-$WORKSPACE_DIR/models/Qwen3.5-4B}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-1,3,4,5,6,7}"
export HOTPOTQA_NUM_GPUS="${HOTPOTQA_NUM_GPUS:-6}"
export HOTPOTQA_AGENT_WORKERS="${HOTPOTQA_AGENT_WORKERS:-6}"
export HOTPOTQA_VLLM_GPU_MEMORY_UTILIZATION="${HOTPOTQA_VLLM_GPU_MEMORY_UTILIZATION:-0.25}"
export HOTPOTQA_VLLM_MAX_MODEL_LEN="${HOTPOTQA_VLLM_MAX_MODEL_LEN:-8192}"
export HOTPOTQA_VLLM_MAX_NUM_BATCHED_TOKENS="${HOTPOTQA_VLLM_MAX_NUM_BATCHED_TOKENS:-8192}"
export HOTPOTQA_VLLM_MAX_NUM_SEQS="${HOTPOTQA_VLLM_MAX_NUM_SEQS:-20}"
export HOTPOTQA_VLLM_KV_CACHE_MEMORY_BYTES="${HOTPOTQA_VLLM_KV_CACHE_MEMORY_BYTES:-2147483648}"
export HOTPOTQA_ROLLOUT_N="${HOTPOTQA_ROLLOUT_N:-4}"
export HOTPOTQA_TRAIN_MAX_SAMPLES=30000
export HOTPOTQA_TRAIN_BATCH_SIZE=20
export HOTPOTQA_GRPO_MICRO_BATCH_SIZE="${HOTPOTQA_GRPO_MICRO_BATCH_SIZE:-2}"
export HOTPOTQA_TOTAL_TRAINING_STEPS=1500
export HOTPOTQA_DATA_SHUFFLE=false
export HOTPOTQA_SAVE_FREQ=50
export HOTPOTQA_MAX_ACTOR_CKPT_TO_KEEP=2
export HOTPOTQA_SKIP_PREFLIGHT="${HOTPOTQA_SKIP_PREFLIGHT:-1}"
export RUN_ID="${RUN_ID:-qwen35-4b_a8_lr30_claimsource_em100_main30k_n4_1500step_6gpu_vllm025_mlen8192_mseq20_save50_$(date +%Y%m%d-%H%M%S)}"
export HOTPOTQA_OUTPUT_DIR="${HOTPOTQA_OUTPUT_DIR:-$WORKSPACE_DIR/logs/$RUN_ID}"

exec bash "$PROJECT_DIR/examples/hotpotqa/run_rlvr.sh"
